[workspace]
members = [
  "crates/opentray-backend-ksni",
  "crates/opentray-backend-tray-icon",
  "crates/opentray-bin",
  "crates/opentray-core",
  "crates/opentray-spec",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/jixoai/opentray"
rust-version = "1.80"
version = "0.0.0"

[workspace.dependencies]
opentray-backend-ksni = { path = "crates/opentray-backend-ksni", version = "0.0.0" }
opentray-backend-tray-icon = { path = "crates/opentray-backend-tray-icon", version = "0.0.0" }
opentray-core = { path = "crates/opentray-core", version = "0.0.0" }
opentray-spec = { path = "crates/opentray-spec", version = "0.0.0" }
ksni = "0.3.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tray-icon = { version = "0.24.0", default-features = false }
