[package]
name = "opentray-ext-lynx"
description = "OpenTray Lynx dynamic extension ABI provider."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
opentray-spec.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
