// Orthogonal intents (2026-08-16, updated 2026-08-19 and 2026-09-11; owner
// round-9 demands: startup terminal PTY streaming, shell window, tray icon
// wiring, multi-port monitor with (detached) title marking; 2026-08-19
// decisions D1–D6 in
// openspec/changes/create-no-first-launch-force-terminal/plans/plan.md made
// the PTY unconditional, removed the blocking service-port gate, made service
// discovery an unbounded adaptive monitor, and turned the terminal window
// into the abnormal-exit surface; add-webview-orchestration D13, 2026-09-11,
// composed toolbar service windows over that base):
// 1. Render the generated app entry from the frozen config as one real TS
//    template literal (compile-checked here; no string surgery at build time).
// 2. Command supervision: the command ALWAYS runs through a PTY
//    (preview-parity TTY environment; a failed PTY load degrades to pipes and
//    logs the degradation), and teardown sweeps the whole process tree
//    (group signal + PPid walk, SIGTERM → bounded grace → SIGKILL).
// 3. Service windows are driven exclusively by the continuous adaptive port
//    monitor — one window per HTTP-verified port, no startup gate, no
//    deadline; polling cost is bounded by cadence (≈1s active, ≤5s quiet or
//    under load), never by a time limit. Toolbar service windows (D13)
//    compose the SAME native navigation-toolbar carrier URL applications use
//    (toolbar webview + content webview + column layout + channel
//    navigation) over each dedicated service window; the legacy
//    showAddressBar iframe wrapper is gone, no generated payload ships an
//    iframe-wrapped service window, and PTY/port supervision laws are
//    unchanged (the toolbar composes the window; it never supervises).
// 4. Terminal window: `showTerminal` controls initial visibility only; an
//    abnormal command exit (non-zero/signal code, or exit before any verified
//    service) force-reveals it with the retained output replay.
// 5. Observability (Codex R2 P1 + R3, 2026-09-15): bootstrap milestone and
//    error records flow through the embedded serial append queue — app.log
//    receives milestones in execution order and every exit path awaits the
//    drain (no reordering between concurrent appendFile completions, no
//    record lost to a fast process.exit) — supervised-command output chunks
//    flow through the bounded coalescing output channel instead of that
//    chain, and any startup failure persists its stack to app.log before
//    exit(1).
import type { ScaffoldAppConfig } from "./scaffold";
import { toolbarCarrierSource } from "./toolbar-carrier";
import { logQueueSource } from "./log-queue";

/** The generated app entry: supervises the command, owns tray + window. */
export const createEntrySource = (config: ScaffoldAppConfig): string => {
  if (config.command === undefined) {
    throw new Error("command entry template requires a command source");
  }
  return `#!/usr/bin/env node
// Generated by create-opentray. Supervises the recorded command and hosts it
// in an OpenTray tray + appMode window. Quit lives in the tray menu.
import { spawn, execFile, spawnSync } from "node:child_process";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import http from "node:http";
import { cpus, loadavg } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createTray } from "opentray";
import { WebviewExt, column, fixed, grow } from "@opentray/ext-webview";

const PROJECT_DIR = dirname(fileURLToPath(import.meta.url));

// App Launch Law: persist the ABSOLUTE JS runtime. Under a Bun-hosted
// wizard, execPath is bun — resolve node's real path once at startup
// instead of persisting a bare PATH lookup (launchd's PATH is minimal).
const nodeRuntime = () => {
  if (process.versions.bun === undefined) return process.execPath;
  try {
    const found = spawnSync("which", ["node"], { encoding: "utf8" }).stdout?.trim() ?? "";
    if (found.length > 0) return found;
  } catch { /* fall through */ }
  return "node";
};

const config = ${JSON.stringify(config, null, 2)};

const appLogPath = resolve(PROJECT_DIR, "app.log");
await mkdir(dirname(appLogPath), { recursive: true });
${logQueueSource()}
const logNote = (message) => { void logSink("[create-opentray] " + message + "\\n", "utf8"); };
// Bootstrap milestones (harden-lifecycle-ownership D5): one structured JSON
// record per startup step — the operator reads session health from app.log
// alone, and a failed step names itself instead of needing archaeology.
const errorText = (error) => error instanceof Error ? error.message : String(error);
const logEvent = (record) => logSink(JSON.stringify({ time: new Date().toISOString(), event: "bootstrap", ...record }) + "\\n", "utf8");
const sleep = (ms) => new Promise((resolvePromise) => setTimeout(resolvePromise, ms));

const shellOptions = ${JSON.stringify(config.shell ?? null)};
const showTerminal = shellOptions !== null && shellOptions.showTerminal === true;
// Toolbar carrier (add-webview-orchestration D13): window.toolbar is the one
// canonical toolbar fact for BOTH application forms; the retired legacy shell
// address-bar input is deliberately not read (stale frozen occurrences are
// ignored by loose parsing).
const toolbarMode = config.window.toolbar === true;
const titleFollows = config.window.titleFollowsDocument !== false;
const iconFollows = config.window.iconFollowsDocument === true;

${toolbarCarrierSource()}

// Configured env overlay (advanced command options); empty by default.
const commandEnv = ${JSON.stringify(config.command.env ?? {})};

const httpAnswers = (port) => new Promise((resolvePromise) => {
  const request = http.get({ host: "127.0.0.1", port, path: "/", timeout: 1500 }, (response) => {
    response.resume();
    resolvePromise(response.statusCode !== undefined && response.statusCode > 0);
  });
  request.once("timeout", () => { request.destroy(); resolvePromise(false); });
  request.once("error", () => resolvePromise(false));
});

const listProcessTreePids = async (rootPid) => {
  if (process.platform === "win32") return [rootPid];
  const pids = new Set([rootPid]);
  const frontier = [rootPid];
  while (frontier.length > 0) {
    const pid = frontier.pop();
    const children = await new Promise((resolvePromise) => {
      execFile("pgrep", ["-P", String(pid)], (error, stdout) => {
        resolvePromise(error ? [] : stdout.split("\\n").map((line) => Number(line)).filter((n) => Number.isInteger(n) && n > 0));
      });
    });
    for (const child of children) {
      if (!pids.has(child)) { pids.add(child); frontier.push(child); }
    }
  }
  return [...pids];
};

const listOwnedListeningPorts = async (rootPid) => {
  if (process.platform === "win32") return [];
  const mine = new Set((await listProcessTreePids(rootPid)).map((pid) => String(pid)));
  const output = await new Promise((resolvePromise) => {
    execFile("lsof", ["-F", "pPn", "-nP", "-i", "TCP", "-sTCP:LISTEN"], (error, stdout) => {
      resolvePromise(error ? "" : stdout);
    });
  });
  const ports = new Set();
  let currentPid = "";
  for (const line of output.split("\\n")) {
    if (line.length === 0) continue;
    const tag = line[0];
    const value = line.slice(1);
    if (tag === "p") currentPid = value;
    else if (tag === "n" && currentPid !== "" && mine.has(currentPid)) {
      const port = Number(value.split(":").pop());
      if (Number.isInteger(port) && port > 0) ports.add(port);
    }
  }
  return [...ports];
};

const main = async () => {
  let appIcon;
  try {
    const manifest = JSON.parse(await readFile(resolve(PROJECT_DIR, "app-icon", "app-icon.json"), "utf8"));
    // The manifest stores project-relative source paths; OpenTray validates file
    // sources against the caller's cwd, so canonicalize them to absolute paths
    // before dispatch (a reused broker cwd must never reinterpret App identity).
    appIcon = manifest.appIcon.map((asset) => (
      asset.source?.type === "file" && !asset.source.path.startsWith("/")
        ? { ...asset, source: { ...asset.source, path: resolve(PROJECT_DIR, "app-icon", asset.source.path) } }
        : asset
    ));
  } catch {
    appIcon = undefined;
  }

  // Shell host (D2): unconditional — the terminal window is every app's
  // abnormal-exit surface, and the toolbar carrier's page asset is served
  // from the same host (its navigation surface stays channel-only, D12).
  const shellApi = await import("./app-shell-server.mjs");
  const shellPort = await shellApi.listenShell();
  if (shellPort === null) {
    await logEvent({ step: "listenShell", status: "failed" });
  } else {
    void logEvent({ step: "listenShell", status: "ok", port: shellPort });
  }

  // Command supervision state shared by the exit note and teardown.
  let commandExited = false;
  let sawVerifiedService = false;

  // D4: the command ALWAYS runs through a PTY — the same TTY environment the
  // wizard preview used. A failed native-PTY load degrades to pipes.
  let ptyModule;
  try {
    ptyModule = await import("@lydell/node-pty");
  } catch {
    ptyModule = null;
  }
  const cwd = resolve(PROJECT_DIR, config.command.cwd);
  let command;
  if (ptyModule !== null) {
    const pty = ptyModule.spawn(config.command.command, [...config.command.args], {
      name: "xterm-256color",
      cols: 100,
      rows: 30,
      cwd,
      env: { ...process.env, ...commandEnv, TERM: "xterm-256color" },
    });
    shellApi.registerPty(pty);
    pty.onData((chunk) => {
      // Child output is bounded-channel data (Codex R3), never a milestone
      // record — a noisy command must not tax the serial chain.
      logOutputChunk(chunk);
      shellApi.pushOutput(chunk);
    });
    const exited = new Promise((resolvePromise) => {
      pty.onExit(({ exitCode, signal }) => resolvePromise({ code: exitCode, signal }));
    });
    command = {
      pid: pty.pid,
      exited,
      killDirect: () => { try { pty.kill(); } catch { /* already dead */ } },
    };
  } else {
    await logSink("[create-opentray] @lydell/node-pty unavailable; command degraded to pipes (no TTY)\\n", "utf8");
    const child = spawn(config.command.command, [...config.command.args], {
      cwd,
      // stdin stays an unwritten pipe: interactive commands must not see EOF.
      stdio: ["pipe", "pipe", "pipe"],
      env: { ...process.env, ...commandEnv },
      windowsHide: true,
      detached: process.platform !== "win32", // own process group → group teardown
    });
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => { logOutputChunk(chunk); shellApi.pushOutput(chunk); });
    child.stderr.on("data", (chunk) => { logOutputChunk(chunk); shellApi.pushOutput(chunk); });
    const exited = new Promise((resolvePromise) => {
      child.once("exit", (code, signal) => resolvePromise({ code, signal }));
    });
    command = {
      pid: child.pid,
      exited,
      killDirect: () => { try { child.kill("SIGTERM"); } catch { /* already dead */ } },
    };
  }

  const trayIcon = ${JSON.stringify(config.trayIcon ?? null)};
  const trayIconCandidates = trayIcon === null
    ? {}
    : trayIcon.template && process.platform === "darwin"
      ? { "darwin-icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path), isTemplate: true } }
      : { "icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path) } };

  const tray = await (async () => {
    try {
      const created = await createTray({
        id: config.appId,
        tooltip: { title: config.appName, description: \`\${config.appName} (OpenTray)\` },
        icon: Object.keys(trayIconCandidates).length > 0
          ? trayIconCandidates
          : { "text-only": "${config.appName.replace(/['"\\]/gu, "").slice(0, 2) || "A"}" },
        menu: { items: [
          { type: "item", id: 1, title: \`Show \${config.appName}\`, primaryEvent: true },
          { type: "separator" },
          { type: "item", id: 2, title: "Quit" },
        ] },
      }, {
        appId: config.appId,
        appName: config.appName,
        ...(appIcon === undefined ? {} : { appIcon }),
        appLaunch: {
          // The generated entry embeds a native PTY (@lydell/node-pty), which
          // requires a Node host — cold launches must not inherit a Bun execPath.
          command: nodeRuntime(),
          args: [resolve(PROJECT_DIR, "main.mjs")],
          cwd: PROJECT_DIR,
        },
      });
      void logEvent({ step: "createTray", status: "ok", appId: config.appId });
      return created;
    } catch (error) {
      // Carrier-resurrection yield: a Dock-pinned carrier can cold-start this
      // entry while another instance already owns the broker session. The
      // owner keeps the app open; this launcher exits cleanly (no retry, no
      // empty tray shell, no orphaned command supervision) and the evidence
      // lands in app.log. The supervised command started BEFORE createTray,
      // so the yield takes it down (direct kill; the closing PTY master adds
      // SIGHUP) — the shell server dies with this process.
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes("OPENTRAY_BROKER_SINGLE_SESSION")) {
        await logSink("[create-opentray] broker session already owned by another instance of this app; this cold-started launcher exits (yield)\\n", "utf8");
        try { command.killDirect(); } catch { /* already dead */ }
        await flushLogQueue();
        process.exit(0);
      }
      throw error;
    }
  })();

  // harden-lifecycle-ownership D3: broker connection death is a terminal
  // state. The entry records the milestone and exits non-zero — the
  // supervised command dies with its supervisor instead of outliving a dead
  // backend. The quitting flag keeps the graceful quit path (whose transport
  // close also reaches this terminal state) on its exit(0) course.
  let quitting = false;
  tray.onConnectionDead?.((error) => {
    if (quitting) return;
    quitting = true;
    void (async () => {
      await logEvent({ step: "connectionDead", status: "failed", error: errorText(error) });
      await flushLogQueue();
      process.exit(1);
    })();
  });

  const baseTitle = config.appName;
  // v1 developerMode maps ONLY to per-window DevTools admission. When false it
  // must not request devtools at all — default windows are not inspectable.
  const devtools = config.developerMode === true ? { devtools: true } : {};

  // Dedicated windows: one terminal window (always available; initially
  // visible only under showTerminal), one window per listened port — the
  // native toolbar carrier when window.toolbar is on, the direct service URL
  // otherwise. Each window gets its OWN extension mount (tray.extend per
  // window = its own window session), so dedicated windows never collide on
  // content.
  const serviceWindows = new Map();
  // harden-lifecycle-ownership D5: a port whose window bootstrap failed is
  // recorded once (app.log names the failed milestone) and not retried every
  // monitor tick — a zombie retry loop would bury the failure record.
  const failedServiceWindows = new Set();
  let terminalWindow = null;

  const ensureTerminalWindow = async () => {
    if (terminalWindow !== null || shellPort === null) return terminalWindow;
    const candidate = tray.extend(WebviewExt).createWebviewWindow({
      url: \`http://127.0.0.1:\${shellPort}/terminal.html\`,
      width: 900,
      height: 560,
      title: \`\${baseTitle} — Terminal\`,
      style: { appMode: true, autoHide: false, keepOnTop: false },
      ...devtools,
    });
    // D5: a failed show leaves no session — record it and keep
    // terminalWindow null so a later abnormal-exit reveal can retry this
    // surface against a fresh window.
    try {
      await candidate.show();
      void logEvent({ step: "showWindow", status: "ok", target: "terminal" });
    } catch (error) {
      await logEvent({ step: "showWindow", status: "failed", target: "terminal", error: errorText(error) });
      await candidate.destroy().catch(() => {});
      return null;
    }
    terminalWindow = candidate;
    return terminalWindow;
  };

  // D2: abnormal exit force-reveals the terminal window regardless of the
  // showTerminal config. The shell host's output ring replays the full
  // history to a window opened here for the first time.
  const revealTerminalWindow = async () => {
    if (terminalWindow === null) {
      await ensureTerminalWindow();
      return;
    }
    await terminalWindow.toVisible().catch(() => {});
    await terminalWindow.focus().catch(() => {});
  };

  const ensureServiceWindow = async (port) => {
    if (serviceWindows.has(port) || failedServiceWindows.has(port)) return;
    const direct = \`http://127.0.0.1:\${port}\`;
    // Toolbar service windows (D13): the SAME native carrier URL applications
    // use — a windowOnly session whose toolbar webview (shell-served
    // toolbar page) sits above a content webview loading the verified
    // service URL directly (no iframe wrapper, no bridge on the content
    // side, no embedding-policy consultation). Direct service windows keep
    // the D13 native sync defaults unchanged.
    if (toolbarMode && shellPort !== null) {
      const win = tray.extend(WebviewExt).createWebviewWindow({
        windowOnly: true,
        width: config.window.width,
        height: config.window.height,
        title: baseTitle,
        style: { appMode: true, autoHide: false, keepOnTop: false },
        ...devtools,
      });
      // harden-lifecycle-ownership D5: the show() before the carrier is a
      // bootstrap gate — a failure aborts (the carrier never attaches child
      // webviews against a session that never came up) and the structured
      // record names the failed milestone in app.log.
      try {
        await win.show();
        void logEvent({ step: "showWindow", status: "ok", target: "service", port });
      } catch (error) {
        await logEvent({ step: "showWindow", status: "failed", target: "service", port, error: errorText(error) });
        failedServiceWindows.add(port);
        await win.destroy().catch(() => {});
        return;
      }
      try {
        const carrier = await attachToolbarCarrier(win, {
          toolbarUrl: \`http://127.0.0.1:\${shellPort}/toolbar.html\`,
          contentUrl: direct,
          titleFollows,
          log: logNote,
          event: logEvent,
        });
        // P1-3 exit race: teardown closes the channel; the carrier must never
        // rebuild against a dying session. Stop before the window goes down.
        process.once("exit", carrier.stop);
      } catch {
        // D5: the carrier already recorded its failed milestone; this window
        // is dead, the port is not retried, and the supervised command keeps
        // running (its terminal remains the abnormal-exit surface).
        failedServiceWindows.add(port);
        await win.destroy().catch(() => {});
        return;
      }
      serviceWindows.set(port, { win, detached: false });
      return;
    }
    const win = tray.extend(WebviewExt).createWebviewWindow({
      url: direct,
      width: config.window.width,
      height: config.window.height,
      title: baseTitle,
      style: { appMode: true, autoHide: false, keepOnTop: false },
      ...devtools,
      ...(!titleFollows ? {} : { titleSync: { documentToWindow: true } }),
      ...(!iconFollows ? {} : { iconSync: { faviconToWindow: true } }),
    });
    try {
      await win.show();
      void logEvent({ step: "showWindow", status: "ok", target: "service", port });
    } catch (error) {
      await logEvent({ step: "showWindow", status: "failed", target: "service", port, error: errorText(error) });
      failedServiceWindows.add(port);
      await win.destroy().catch(() => {});
      return;
    }
    serviceWindows.set(port, { win, detached: false });
  };

  if (showTerminal) {
    await ensureTerminalWindow();
  }

  // D5: teardown sweeps the WHOLE process tree. POSIX pipe fallbacks run in
  // an owned process group (detached spawn) so the group signal reaches
  // children that ignored the direct one; setsid escapees fall to the PPid
  // walk. Escalation: SIGTERM (direct + group + tree) → 3s grace → SIGKILL.
  const killCommand = async () => {
    if (process.platform === "win32") {
      await new Promise((resolvePromise) => {
        execFile("taskkill", ["/PID", String(command.pid), "/T", "/F"], () => resolvePromise());
      });
      return;
    }
    const tree = await listProcessTreePids(command.pid).catch(() => [command.pid]);
    if (!commandExited) command.killDirect();
    try { process.kill(-command.pid, "SIGTERM"); } catch { /* group gone */ }
    for (const pid of tree) { try { process.kill(pid, "SIGTERM"); } catch { /* raced exit */ } }
    if (!commandExited) await Promise.race([command.exited, sleep(3000)]);
    const survivors = [];
    for (const pid of tree) {
      try { process.kill(pid, 0); survivors.push(pid); } catch { /* dead */ }
    }
    if (survivors.length > 0 || !commandExited) {
      try { process.kill(-command.pid, "SIGKILL"); } catch { /* group gone */ }
      for (const pid of survivors) { try { process.kill(pid, "SIGKILL"); } catch { /* raced exit */ } }
    }
    await Promise.race([command.exited, sleep(1000)]);
  };

  // Abnormal-exit detection (D2): non-zero/signal code, or exit before ANY
  // verified service. The note enters app.log AND the shell output ring so a
  // force-revealed terminal window shows why it appeared.
  void command.exited.then(async ({ code, signal }) => {
    commandExited = true;
    // @lydell/node-pty reports signal 0 (not undefined) on normal exits.
    const hadSignal = signal !== undefined && signal !== null && signal !== 0;
    const detail = hadSignal ? \`signal \${signal}\` : \`code \${code}\`;
    const abnormal = code !== 0 || hadSignal || !sawVerifiedService;
    const why = abnormal ? (code === 0 && !hadSignal ? " before any service appeared" : "") : "";
    const note = \`[create-opentray] command exited (\${detail})\${why}\${abnormal ? " — revealing terminal" : ""}\\n\`;
    await logSink(note, "utf8");
    shellApi.pushOutput(note);
    if (abnormal) await revealTerminalWindow();
  });

  {
    // D3: unbounded adaptive service monitor. Polling cost law: ≈1s while
    // anything changes, backing off to ≤5s when quiet or when 1-min load
    // exceeds the core count — 0.2–1Hz, never a hidden high-frequency loop,
    // never a deadline. Ports come EXCLUSIVELY from owned-tree sniffing plus
    // HTTP verification (dynamic ports behave like fixed ones).
    const FAST_INTERVAL_MS = 1000;
    const SLOW_INTERVAL_MS = 5000;
    const QUIET_TICKS_BEFORE_BACKOFF = 8;
    const cpuCount = cpus().length;
    const seenPorts = new Set();
    const verifiedPorts = new Set();
    let lastSignature = "";
    let quietTicks = 0;
    let stopped = false;
    const nextIntervalMs = () => {
      const loadBusy = (loadavg()[0] ?? 0) > cpuCount;
      return quietTicks >= QUIET_TICKS_BEFORE_BACKOFF || loadBusy ? SLOW_INTERVAL_MS : FAST_INTERVAL_MS;
    };
    const monitorTick = async () => {
      const owned = await listOwnedListeningPorts(command.pid).catch(() => []);
      const listening = owned.filter((port) => port > 0);
      for (const port of listening) {
        if (!verifiedPorts.has(port) && (await httpAnswers(port))) {
          verifiedPorts.add(port);
        }
      }
      if (verifiedPorts.size > 0) sawVerifiedService = true;
      for (const port of verifiedPorts) seenPorts.add(port);
      const services = [...seenPorts].map((port) => ({
        port,
        detached: !listening.includes(port),
      }));
      shellApi.setServices(services);
      for (const service of services) {
        if (!service.detached) await ensureServiceWindow(service.port);
        const entry = serviceWindows.get(service.port);
        if (entry !== undefined && Boolean(entry.detached) !== Boolean(service.detached)) {
          entry.detached = Boolean(service.detached);
          const title = service.detached ? \`\${baseTitle} (detached)\` : baseTitle;
          await entry.win.setTitle(title).catch(() => {});
        }
      }
      const signature = JSON.stringify([services, listening]);
      const changed = signature !== lastSignature;
      lastSignature = signature;
      return changed;
    };
    const runMonitor = async () => {
      while (!stopped) {
        let changed = false;
        try {
          changed = await monitorTick();
        } catch {
          /* monitor tick */
        }
        quietTicks = changed ? 0 : quietTicks + 1;
        await sleep(nextIntervalMs());
      }
    };
    void runMonitor();
    process.once("exit", () => { stopped = true; });
  }

  const quit = async () => {
    quitting = true;
    for (const { win } of serviceWindows.values()) {
      try { await win.destroy(); } catch {}
    }
    serviceWindows.clear();
    if (terminalWindow !== null) {
      try { await terminalWindow.destroy(); } catch {}
    }
    await tray.destroy();
    await killCommand();
    await flushLogQueue();
    process.exit(0);
  };

  tray.onMenuClick(({ itemId }) => {
    if (itemId === 1) {
      const target = terminalWindow !== null
        ? terminalWindow
        : serviceWindows.size > 0
          ? [...serviceWindows.values()][0].win
          : null;
      if (target === null) return;
      void target.isVisible().then(async (visible) => {
        if (visible) { await target.close(); } else { await target.toVisible(); }
      }).catch(() => {});
      return;
    }
    if (itemId === 2) void quit();
  });

  process.on("SIGINT", () => void quit());
  process.on("SIGTERM", () => void quit());
};

// D6: no startup failure is silent — the stack lands in app.log (the entry's
// only durable surface when the tray itself never came up) before exit(1).
main().catch(async (error) => {
  try {
    await logSink(\`[create-opentray] startup failed: \${error instanceof Error ? error.stack ?? error.message : String(error)}\\n\`, "utf8");
  } catch { /* app.log unwritable; stderr below is the remaining surface */ }
  console.error(error);
  await flushLogQueue();
  process.exit(1);
});
`;
};
