// Orthogonal intents (2026-08-16; owner round-9 demand: the generated app may
// embed the SAME terminal/iframe tab experience the wizard has):
// 1. Render the generated app's shell-server entry source from a frozen config.
// 2. Serve prebuilt shell UI statically + SSE state (command, PTY ring, ports).
// 3. Accept terminal input routed to the PTY registered by main.mjs.
// 4. Report owned-port lifecycles so the shell can auto-open tabs and mark
//    detached services; main.mjs owns detection and calls setServices.
// Kept physically separate from scaffold.ts: the template's nested JS template
// literals are hostile to inline embedding.

/** The generated app's local shell host: static UI + PTY stream + port state. */
export const shellServerSource = (options: {
  readonly commandDisplay: string;
}): string => `#!/usr/bin/env node
// Generated by create-opentray. Local shell host: static UI + PTY stream + port state.
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join, normalize, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const PROJECT_DIR = dirname(fileURLToPath(import.meta.url));
const SHELL_DIR = resolve(PROJECT_DIR, "app-shell");

// --- state shared with the shell UI ---
const state = {
  command: ${JSON.stringify(options.commandDisplay)},
  interactive: false, // main.mjs flips this when a PTY is attached
  output: [],         // ring of PTY chunks
  services: [],       // [{ port, detached }]
  listeners: new Set(), // SSE response streams
};
const RING_LIMIT = 2000;

const emit = (event) => {
  const frame = \`data: \${JSON.stringify(event)}\n\n\`;
  for (const res of state.listeners) {
    try {
      res.write(frame);
    } catch {
      /* dropped client */
    }
  }
};

const snapshot = () => ({
  type: "state",
  command: state.command,
  interactive: state.interactive,
  services: state.services,
  output: state.output.slice(-400),
});

/** main.mjs registers the live PTY handle here. */
export const registerPty = (pty) => {
  state.pty = pty;
  state.interactive = pty !== null && pty !== undefined;
};

/** main.mjs forwards PTY output chunks here. */
export const pushOutput = (chunk) => {
  state.output.push(chunk);
  if (state.output.length > RING_LIMIT) {
    state.output.splice(0, state.output.length - RING_LIMIT);
  }
  emit({ type: "log", chunk });
};

/** main.mjs reports the owned-port snapshot; detached flags drive title marks. */
export const setServices = (services) => {
  const changed =
    services.length !== state.services.length ||
    services.some(
      (s, i) =>
        state.services[i] === undefined ||
        s.port !== state.services[i].port ||
        Boolean(s.detached) !== Boolean(state.services[i].detached),
    );
  state.services = services;
  if (changed) {
    emit({ type: "services", services });
  }
};

const CT = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".wasm": "application/wasm",
  ".json": "application/json",
};

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? "/", "http://127.0.0.1");
  if (url.pathname === "/api/events") {
    res.writeHead(200, {
      "content-type": "text/event-stream",
      "cache-control": "no-store",
      connection: "keep-alive",
    });
    res.write(\`data: \${JSON.stringify(snapshot())}\n\n\`);
    state.listeners.add(res);
    req.on("close", () => {
      state.listeners.delete(res);
    });
    return;
  }
  if (url.pathname === "/api/terminal-input" && req.method === "POST") {
    let body = "";
    for await (const chunk of req) {
      body += chunk;
    }
    try {
      const { data } = JSON.parse(body);
      if (state.pty !== null && state.pty !== undefined && typeof data === "string") {
        state.pty.write(data);
      }
    } catch {
      /* malformed body */
    }
    res.writeHead(200, { "content-type": "application/json" }).end('{"ok":true}');
    return;
  }
  // Static shell files with traversal containment; SPA fallback for routes.
  const relative = normalize(url.pathname).replace(/\\/(\\.\\.\\/?)*/, "");
  const target = resolve(
    SHELL_DIR,
    relative === "" || relative === "/" ? "index.html" : relative,
  );
  if (target !== SHELL_DIR && !target.startsWith(SHELL_DIR + sep)) {
    res.writeHead(404).end();
    return;
  }
  const bytes = await readFile(target).catch(() => undefined);
  if (bytes === undefined) {
    const index = await readFile(join(SHELL_DIR, "index.html")).catch(() => undefined);
    if (index === undefined) {
      res.writeHead(404).end();
      return;
    }
    res
      .writeHead(200, { "content-type": CT[".html"], "cache-control": "no-store" })
      .end(index);
    return;
  }
  res
    .writeHead(200, {
      "content-type": CT[extname(target).toLowerCase()] ?? "application/octet-stream",
      "cache-control": "no-store",
    })
    .end(bytes);
});

/** Start listening on an ephemeral loopback port; resolves the port. */
export const listenShell = () =>
  new Promise((resolvePort) => {
    server.listen(0, "127.0.0.1", () => {
      resolvePort(server.address().port);
    });
  });
`;
