// Orthogonal intents (2026-09-09, openspec change add-create-url-apps; original
// user request: create-opentray packages a URL directly as an application;
// acceptance round 3 adds tray reload and durable sync defaults D11–D13;
// add-webview-orchestration D12/D13 replace the iframe wrapper carrier with
// the multi-webview toolbar carrier, 2026-09-11):
// 1. Render the URL app entry from the frozen config as one real TS template
//    literal (compile-checked here; no string surgery at build time).
// 2. Direct mode: one application-mode WebView window targets the frozen URL;
//    title follows the document one-way by default, icon following is opt-in
//    (D13). No PTY, no port monitor: a URL application supervises nothing.
// 3. Toolbar mode (D12/D13): the window is a windowOnly session composed of
//    one toolbar webview (shell-served toolbar page, bridge { webviewId,
//    messageChannels }) and one content webview loading the recorded URL
//    directly as a top-level browsing context (no bridge = bridgeless), laid
//    out by column([fixed("toolbar", 44), grow("content")]). Embedding policy
//    (X-Frame-Options / CSP frame-ancestors) is not consulted — a top-level
//    content webview is not an embedded context (D14). The payload carries
//    the shell server + toolbar assets and still no PTY dependency.
// 4. Lifecycle: the tray menu offers Reload (D11; toolbar mode reloads the
//    CONTENT webview through the native navigate command, direct mode keeps
//    the evaluate channel, and the app process never restarts for a reload);
//    Quit destroys the window and tray session and exits — there is no child
//    process tree to sweep (D9).
// 5. Observability (Codex R2 P1 + R3, 2026-09-15): milestone and error
//    records flow through the embedded serial append queue — app.log
//    receives milestones in execution order and every exit path awaits the
//    drain (no reordering between concurrent appendFile completions, no
//    record lost to a fast process.exit; a URL app has no child output, so
//    the bounded output channel stays defined-but-unused) — and any startup
//    failure persists its stack to app.log before exit(1).
import type { ScaffoldAppConfig } from "./scaffold";
import { toolbarCarrierSource } from "./toolbar-carrier";
import { logQueueSource } from "./log-queue";

/** The generated URL app entry: owns tray + one direct or toolbar-carrier window. */
export const createUrlEntrySource = (config: ScaffoldAppConfig): string => {
  if (config.url === undefined) {
    throw new Error("URL entry template requires a url source");
  }
  return `#!/usr/bin/env node
// Generated by create-opentray. Hosts the recorded URL in an OpenTray tray +
// appMode window. Quit lives in the tray menu.
import { spawnSync } from "node:child_process";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createTray } from "opentray";
import { WebviewExt, column, fixed, grow } from "@opentray/ext-webview";

const PROJECT_DIR = dirname(fileURLToPath(import.meta.url));

// App Launch Law: persist the ABSOLUTE JS runtime. Under a Bun-hosted
// wizard, execPath is bun — resolve node's real path once at startup
// instead of persisting a bare PATH lookup (launchd's PATH is minimal).
const nodeRuntime = () => {
  if (process.versions.bun === undefined) return process.execPath;
  try {
    const found = spawnSync("which", ["node"], { encoding: "utf8" }).stdout?.trim() ?? "";
    if (found.length > 0) return found;
  } catch { /* fall through */ }
  return "node";
};

const config = ${JSON.stringify(config, null, 2)};
const toolbarMode = config.window.toolbar === true;
const titleFollows = config.window.titleFollowsDocument !== false;
const iconFollows = config.window.iconFollowsDocument === true;

const appLogPath = resolve(PROJECT_DIR, "app.log");
await mkdir(dirname(appLogPath), { recursive: true });
${logQueueSource()}
const logNote = (message) => { void logSink("[create-opentray] " + message + "\\n", "utf8"); };
// Bootstrap milestones (harden-lifecycle-ownership D5): one structured JSON
// record per startup step — the operator reads session health from app.log
// alone, and a failed step names itself instead of needing archaeology.
const errorText = (error) => error instanceof Error ? error.message : String(error);
const logEvent = (record) => logSink(JSON.stringify({ time: new Date().toISOString(), event: "bootstrap", ...record }) + "\\n", "utf8");

${toolbarCarrierSource()}const main = async () => {
  let appIcon;
  try {
    const manifest = JSON.parse(await readFile(resolve(PROJECT_DIR, "app-icon", "app-icon.json"), "utf8"));
    // The manifest stores project-relative source paths; OpenTray validates file
    // sources against the caller's cwd, so canonicalize them to absolute paths
    // before dispatch (a reused broker cwd must never reinterpret App identity).
    appIcon = manifest.appIcon.map((asset) => (
      asset.source?.type === "file" && !asset.source.path.startsWith("/")
        ? { ...asset, source: { ...asset.source, path: resolve(PROJECT_DIR, "app-icon", asset.source.path) } }
        : asset
    ));
  } catch {
    appIcon = undefined;
  }

  const trayIcon = ${JSON.stringify(config.trayIcon ?? null)};
  const trayIconCandidates = trayIcon === null
    ? {}
    : trayIcon.template && process.platform === "darwin"
      ? { "darwin-icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path), isTemplate: true } }
      : { "icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path) } };

  const tray = await (async () => {
    try {
      const created = await createTray({
        id: config.appId,
        tooltip: { title: config.appName, description: \`\${config.appName} (OpenTray)\` },
        icon: Object.keys(trayIconCandidates).length > 0
          ? trayIconCandidates
          : { "text-only": "${config.appName.replace(/['"\\]/gu, "").slice(0, 2) || "A"}" },
        menu: { items: [
          { type: "item", id: 1, title: \`Show \${config.appName}\`, primaryEvent: true },
          { type: "item", id: 3, title: "Reload" },
          { type: "separator" },
          { type: "item", id: 2, title: "Quit" },
        ] },
      }, {
        appId: config.appId,
        appName: config.appName,
        ...(appIcon === undefined ? {} : { appIcon }),
        appLaunch: {
          command: nodeRuntime(),
          args: [resolve(PROJECT_DIR, "main.mjs")],
          cwd: PROJECT_DIR,
        },
      });
      void logEvent({ step: "createTray", status: "ok", appId: config.appId });
      return created;
    } catch (error) {
      // Carrier-resurrection yield: a Dock-pinned carrier can cold-start this
      // entry while another instance already owns the broker session. The
      // owner keeps the app open; this launcher exits cleanly (no retry, no
      // empty tray shell) and the evidence lands in app.log.
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes("OPENTRAY_BROKER_SINGLE_SESSION")) {
        await logSink("[create-opentray] broker session already owned by another instance of this app; this cold-started launcher exits (yield)\\n", "utf8");
        await flushLogQueue();
        process.exit(0);
      }
      throw error;
    }
  })();

  // harden-lifecycle-ownership D3: broker connection death is a terminal
  // state. The entry records the milestone and exits non-zero — it never
  // keeps a live shell server over a dead backend (zombie entry). The
  // quitting flag keeps the graceful quit path (whose transport close also
  // reaches this terminal state) on its exit(0) course.
  let quitting = false;
  tray.onConnectionDead?.((error) => {
    if (quitting) return;
    quitting = true;
    void (async () => {
      await logEvent({ step: "connectionDead", status: "failed", error: errorText(error) });
      await flushLogQueue();
      process.exit(1);
    })();
  });

  // v1 developerMode maps ONLY to per-window DevTools admission. When false it
  // must not request devtools at all — default windows are not inspectable.
  const devtools = config.developerMode === true ? { devtools: true } : {};

  // Toolbar shell host (D12): the shell server serves the toolbar page (and
  // nothing else for a URL app — its navigation surface is channel-only);
  // no PTY is registered because a URL app supervises nothing. This is a
  // LOCAL transport dependency only — never an embedding-policy fallback
  // (embedding policy is not consulted at all, D14).
  let shellPort = null;
  if (toolbarMode) {
    const shellApi = await import("./app-shell-server.mjs");
    shellPort = await shellApi.listenShell();
    if (shellPort === null) {
      await logEvent({ step: "listenShell", status: "failed" });
      await logSink("[create-opentray] toolbar shell host failed to listen; opening the direct window\\n", "utf8");
    } else {
      void logEvent({ step: "listenShell", status: "ok", port: shellPort });
    }
  }
  const toolbarReady = toolbarMode && shellPort !== null;

  // Toolbar carrier (D12/D13): windowOnly session composed of the toolbar +
  // content webviews through attachToolbarCarrier below. Direct mode keeps
  // the single-webview window with the native sync defaults (D13): the title
  // follows the document one-way; icon following is opt-in.
  const window = tray.extend(WebviewExt).createWebviewWindow({
    ...(toolbarReady ? { windowOnly: true } : { url: config.url }),
    width: config.window.width,
    height: config.window.height,
    title: config.appName,
    style: { appMode: true, autoHide: false, keepOnTop: false },
    ...devtools,
    ...(toolbarReady ? {} : {
      ...(titleFollows ? { titleSync: { documentToWindow: true } } : {}),
      ...(iconFollows ? { iconSync: { faviconToWindow: true } } : {}),
    }),
  });
  // harden-lifecycle-ownership D5: the initial show() is a bootstrap gate. A
  // failure aborts the carrier (no child webviews attach against a session
  // that never came up) and reaches the startup boundary — app.log records
  // the failed milestone, then the top-level handler persists the stack and
  // exits non-zero. Never swallowed.
  try {
    await window.show();
    void logEvent({ step: "showWindow", status: "ok", mode: toolbarReady ? "toolbar" : "direct" });
  } catch (error) {
    await logEvent({ step: "showWindow", status: "failed", mode: toolbarReady ? "toolbar" : "direct", error: errorText(error) });
    throw error;
  }

  let content = null;
  if (toolbarReady) {
    const carrier = await attachToolbarCarrier(window, {
      toolbarUrl: \`http://127.0.0.1:\${shellPort}/toolbar.html\`,
      contentUrl: config.url,
      titleFollows,
      log: logNote,
      event: logEvent,
    });
    ({ content } = carrier);
    // P1-3 exit race: teardown closes the channel; the carrier must never
    // rebuild against a dying session. Stop before the window goes down.
    process.once("exit", carrier.stop);
  }

  // Tray reload (D11): toolbar mode reloads the CONTENT webview natively
  // (navigate to its current URL — no wrapper evaluate); direct mode reloads
  // the page in place through the evaluate channel. The app never restarts.
  const reload = async () => {
    try {
      if (content !== null) {
        const { url } = await content.getUrl();
        await content.navigate(url);
        return;
      }
      await window.evaluate("location.reload()");
    } catch { /* window gone */ }
  };

  const quit = async () => {
    quitting = true;
    try { await window.destroy(); } catch {}
    await tray.destroy();
    await flushLogQueue();
    process.exit(0);
  };

  tray.onMenuClick(({ itemId }) => {
    if (itemId === 1) {
      void window.isVisible().then(async (visible) => {
        if (visible) { await window.close(); } else { await window.toVisible(); }
      }).catch(() => {});
      return;
    }
    if (itemId === 3) { void reload(); return; }
    if (itemId === 2) void quit();
  });

  process.on("SIGINT", () => void quit());
  process.on("SIGTERM", () => void quit());
};

// No startup failure is silent — the stack lands in app.log (the entry's only
// durable surface when the tray itself never came up) before exit(1).
main().catch(async (error) => {
  try {
    await logSink(\`[create-opentray] startup failed: \${error instanceof Error ? error.stack ?? error.message : String(error)}\\n\`, "utf8");
  } catch { /* app.log unwritable; stderr below is the remaining surface */ }
  console.error(error);
  await flushLogQueue();
  process.exit(1);
});

`;
};
