// Orthogonal intents (2026-09-09, openspec change add-create-url-apps; original
// user request: create-opentray packages a URL directly as an application;
// acceptance round 3 adds toolbar mode, tray reload, and durable sync
// defaults D11–D13):
// 1. Render the URL app entry from the frozen config as one real TS template
//    literal (compile-checked here; no string surgery at build time).
// 2. Direct mode: one application-mode WebView window targets the frozen URL;
//    title follows the document one-way by default, icon following is opt-in
//    (D13). No PTY, no port monitor: a URL application supervises nothing.
// 3. Toolbar mode (D12): the shell host serves the shared address-bar wrapper
//    and the window loads browse.html?url=<target> — still no PTY dependency.
//    Neither sync option is set: the wrapper document's metadata is not the
//    target page's (same law as command-mode address-bar windows).
// 4. Tray menu offers Reload (D11): the page reloads through the WebView
//    evaluate channel without restarting the app.
// 5. Quit destroys the window and tray session and exits; there is no child
//    process tree to sweep (D9).
// 6. Any startup failure persists its stack to app.log before exit(1).
import type { ScaffoldAppConfig } from "./scaffold";

/** The generated URL app entry: owns tray + one direct or wrapped window. */
export const createUrlEntrySource = (config: ScaffoldAppConfig): string => {
  if (config.url === undefined) {
    throw new Error("URL entry template requires a url source");
  }
  return `#!/usr/bin/env node
// Generated by create-opentray. Hosts the recorded URL in an OpenTray tray +
// appMode window. Quit lives in the tray menu.
import { spawnSync } from "node:child_process";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createTray } from "opentray";
import { WebviewExt } from "@opentray/ext-webview";

const PROJECT_DIR = dirname(fileURLToPath(import.meta.url));

// App Launch Law: persist the ABSOLUTE JS runtime. Under a Bun-hosted
// wizard, execPath is bun — resolve node's real path once at startup
// instead of persisting a bare PATH lookup (launchd's PATH is minimal).
const nodeRuntime = () => {
  if (process.versions.bun === undefined) return process.execPath;
  try {
    const found = spawnSync("which", ["node"], { encoding: "utf8" }).stdout?.trim() ?? "";
    if (found.length > 0) return found;
  } catch { /* fall through */ }
  return "node";
};

const config = ${JSON.stringify(config, null, 2)};
const toolbarMode = config.window.toolbar === true;
const titleFollows = config.window.titleFollowsDocument !== false;
const iconFollows = config.window.iconFollowsDocument === true;

const appLogPath = resolve(PROJECT_DIR, "app.log");
await mkdir(dirname(appLogPath), { recursive: true });
const logSink = appendFile.bind(undefined, appLogPath);

const main = async () => {
  let appIcon;
  try {
    const manifest = JSON.parse(await readFile(resolve(PROJECT_DIR, "app-icon", "app-icon.json"), "utf8"));
    // The manifest stores project-relative source paths; OpenTray validates file
    // sources against the caller's cwd, so canonicalize them to absolute paths
    // before dispatch (a reused broker cwd must never reinterpret App identity).
    appIcon = manifest.appIcon.map((asset) => (
      asset.source?.type === "file" && !asset.source.path.startsWith("/")
        ? { ...asset, source: { ...asset.source, path: resolve(PROJECT_DIR, "app-icon", asset.source.path) } }
        : asset
    ));
  } catch {
    appIcon = undefined;
  }

  const trayIcon = ${JSON.stringify(config.trayIcon ?? null)};
  const trayIconCandidates = trayIcon === null
    ? {}
    : trayIcon.template && process.platform === "darwin"
      ? { "darwin-icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path), isTemplate: true } }
      : { "icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path) } };

  const tray = await createTray({
    id: config.appId,
    tooltip: { title: config.appName, description: \`\${config.appName} (OpenTray)\` },
    icon: Object.keys(trayIconCandidates).length > 0
      ? trayIconCandidates
      : { "text-only": "${config.appName.replace(/['"\\]/gu, "").slice(0, 2) || "A"}" },
    menu: { items: [
      { type: "item", id: 1, title: \`Show \${config.appName}\`, primaryEvent: true },
      { type: "item", id: 3, title: "Reload" },
      { type: "separator" },
      { type: "item", id: 2, title: "Quit" },
    ] },
  }, {
    appId: config.appId,
    appName: config.appName,
    ...(appIcon === undefined ? {} : { appIcon }),
    appLaunch: {
      command: nodeRuntime(),
      args: [resolve(PROJECT_DIR, "main.mjs")],
      cwd: PROJECT_DIR,
    },
  });

  // v1 developerMode maps ONLY to per-window DevTools admission. When false it
  // must not request devtools at all — default windows are not inspectable.
  const devtools = config.developerMode === true ? { devtools: true } : {};

  // Toolbar mode (D12): the shell host serves the shared address-bar wrapper;
  // no PTY is registered because a URL app supervises nothing. The wrapper
  // carries neither sync option — its document metadata is not the target's.
  let shellPort = null;
  if (toolbarMode) {
    const shellApi = await import("./app-shell-server.mjs");
    shellPort = await shellApi.listenShell();
    if (shellPort === null) {
      await logSink("[create-opentray] toolbar shell host failed to listen; falling back to the direct window\\n", "utf8");
    }
  }
  const toolbarUrl = toolbarMode && shellPort !== null
    ? \`http://127.0.0.1:\${shellPort}/browse.html?url=\${encodeURIComponent(config.url)}\`
    : null;

  const window = tray.extend(WebviewExt).createWebviewWindow({
    url: toolbarUrl ?? config.url,
    width: config.window.width,
    height: config.window.height,
    title: config.appName,
    style: { appMode: true, autoHide: false, keepOnTop: false },
    ...devtools,
    // D13 sync defaults project only onto the DIRECT window (toolbar windows
    // set neither: one-way title following; icon following is opt-in).
    ...(toolbarUrl === null
      ? {
          ...(titleFollows ? { titleSync: { documentToWindow: true } } : {}),
          ...(iconFollows ? { iconSync: { faviconToWindow: true } } : {}),
        }
      : {}),
  });
  await window.show().catch(() => {});

  // Tray reload (D11): reload the page in place through the evaluate channel.
  const reload = async () => {
    try {
      await window.evaluate("location.reload()");
    } catch { /* window gone */ }
  };

  const quit = async () => {
    try { await window.destroy(); } catch {}
    await tray.destroy();
    process.exit(0);
  };

  tray.onMenuClick(({ itemId }) => {
    if (itemId === 1) {
      void window.isVisible().then(async (visible) => {
        if (visible) { await window.close(); } else { await window.toVisible(); }
      }).catch(() => {});
      return;
    }
    if (itemId === 3) { void reload(); return; }
    if (itemId === 2) void quit();
  });

  process.on("SIGINT", () => void quit());
  process.on("SIGTERM", () => void quit());
};

// No startup failure is silent — the stack lands in app.log (the entry's only
// durable surface when the tray itself never came up) before exit(1).
main().catch(async (error) => {
  try {
    await logSink(\`[create-opentray] startup failed: \${error instanceof Error ? error.stack ?? error.message : String(error)}\\n\`, "utf8");
  } catch { /* app.log unwritable; stderr below is the remaining surface */ }
  console.error(error);
  process.exit(1);
});

`;
};
