// Orthogonal intents (2026-09-09, openspec change add-create-url-apps; original
// user request: create-opentray packages a URL directly as an application):
// 1. Render the URL app entry from the frozen config as one real TS template
//    literal (compile-checked here; no string surgery at build time).
// 2. One application-mode WebView window targets the frozen URL directly —
//    no PTY, no shell host, no port monitor: a URL application supervises
//    nothing (decision D2 in plans/plan.md).
// 3. Quit destroys the window and tray session and exits; there is no child
//    process tree to sweep (decision D9).
// 4. Any startup failure persists its stack to app.log before exit(1) — the
//    same durable-surface law as the command entry.
import type { ScaffoldAppConfig } from "./scaffold";

/** The generated URL app entry: owns tray + one direct window. */
export const createUrlEntrySource = (config: ScaffoldAppConfig): string => {
  if (config.url === undefined) {
    throw new Error("URL entry template requires a url source");
  }
  return `#!/usr/bin/env node
// Generated by create-opentray. Hosts the recorded URL in an OpenTray tray +
// appMode window. Quit lives in the tray menu.
import { spawnSync } from "node:child_process";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createTray } from "opentray";
import { WebviewExt } from "@opentray/ext-webview";

const PROJECT_DIR = dirname(fileURLToPath(import.meta.url));

// App Launch Law: persist the ABSOLUTE JS runtime. Under a Bun-hosted
// wizard, execPath is bun — resolve node's real path once at startup
// instead of persisting a bare PATH lookup (launchd's PATH is minimal).
const nodeRuntime = () => {
  if (process.versions.bun === undefined) return process.execPath;
  try {
    const found = spawnSync("which", ["node"], { encoding: "utf8" }).stdout?.trim() ?? "";
    if (found.length > 0) return found;
  } catch { /* fall through */ }
  return "node";
};

const config = ${JSON.stringify(config, null, 2)};

const appLogPath = resolve(PROJECT_DIR, "app.log");
await mkdir(dirname(appLogPath), { recursive: true });
const logSink = appendFile.bind(undefined, appLogPath);

const main = async () => {
  let appIcon;
  try {
    const manifest = JSON.parse(await readFile(resolve(PROJECT_DIR, "app-icon", "app-icon.json"), "utf8"));
    // The manifest stores project-relative source paths; OpenTray validates file
    // sources against the caller's cwd, so canonicalize them to absolute paths
    // before dispatch (a reused broker cwd must never reinterpret App identity).
    appIcon = manifest.appIcon.map((asset) => (
      asset.source?.type === "file" && !asset.source.path.startsWith("/")
        ? { ...asset, source: { ...asset.source, path: resolve(PROJECT_DIR, "app-icon", asset.source.path) } }
        : asset
    ));
  } catch {
    appIcon = undefined;
  }

  const trayIcon = ${JSON.stringify(config.trayIcon ?? null)};
  const trayIconCandidates = trayIcon === null
    ? {}
    : trayIcon.template && process.platform === "darwin"
      ? { "darwin-icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path), isTemplate: true } }
      : { "icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path) } };

  const tray = await createTray({
    id: config.appId,
    tooltip: { title: config.appName, description: \`\${config.appName} (OpenTray)\` },
    icon: Object.keys(trayIconCandidates).length > 0
      ? trayIconCandidates
      : { "text-only": "${config.appName.replace(/['"\\]/gu, "").slice(0, 2) || "A"}" },
    menu: { items: [
      { type: "item", id: 1, title: \`Show \${config.appName}\`, primaryEvent: true },
      { type: "separator" },
      { type: "item", id: 2, title: "Quit" },
    ] },
  }, {
    appId: config.appId,
    appName: config.appName,
    ...(appIcon === undefined ? {} : { appIcon }),
    appLaunch: {
      command: nodeRuntime(),
      args: [resolve(PROJECT_DIR, "main.mjs")],
      cwd: PROJECT_DIR,
    },
  });

  // v1 developerMode maps ONLY to per-window DevTools admission. When false it
  // must not request devtools at all — default windows are not inspectable.
  const devtools = config.developerMode === true ? { devtools: true } : {};

  // The single direct window (D2): the frozen URL IS the service address.
  // Page metadata sync mirrors the address-bar-less command windows: document
  // titles follow the site and the favicon follows the window.
  const window = tray.extend(WebviewExt).createWebviewWindow({
    url: config.url,
    width: config.window.width,
    height: config.window.height,
    title: config.appName,
    style: { appMode: true, autoHide: false, keepOnTop: false },
    ...devtools,
    titleSync: { documentToWindow: true, windowToDocument: true },
    iconSync: { faviconToWindow: true, windowToFavicon: true },
  });
  await window.show().catch(() => {});

  const quit = async () => {
    try { await window.destroy(); } catch {}
    await tray.destroy();
    process.exit(0);
  };

  tray.onMenuClick(({ itemId }) => {
    if (itemId === 1) {
      void window.isVisible().then(async (visible) => {
        if (visible) { await window.close(); } else { await window.toVisible(); }
      }).catch(() => {});
      return;
    }
    if (itemId === 2) void quit();
  });

  process.on("SIGINT", () => void quit());
  process.on("SIGTERM", () => void quit());
};

// No startup failure is silent — the stack lands in app.log (the entry's only
// durable surface when the tray itself never came up) before exit(1).
main().catch(async (error) => {
  try {
    await logSink(\`[create-opentray] startup failed: \${error instanceof Error ? error.stack ?? error.message : String(error)}\\n\`, "utf8");
  } catch { /* app.log unwritable; stderr below is the remaining surface */ }
  console.error(error);
  process.exit(1);
});
`;
};
