export {
  BrokerServerError,
  createClient,
  createInitFrame,
  createTrayHandle,
  type OpenTrayEventFrame,
  type CreateClientOptions,
  type AppHandle,
  type EventfulTrayHandle,
  type ExtensionLoadOptions,
  type ExtensionRequestResult,
  type OpenTrayConnection,
  type OpenTrayClient,
  type OpenTrayEventSource,
  type OpenTrayTransport,
  type TrayEventByType,
  type TrayEventType,
  type TrayExtension,
  type TrayExtensionContext,
  type TrayExtensionMountSpec,
  type TrayHandle,
} from "./client";
export {
  EMBEDDED_STAGING_MANIFEST_PATH,
  NATIVE_EXTENSION_EMBEDDED_ERROR_CODES,
  NATIVE_EXTENSION_EMBEDDED_TARGET_MATRIX,
  NativeExtensionArtifactResolutionError,
  NativeExtensionEmbeddedArtifactError,
  resolveNativeExtensionArtifact,
  type NativeExtensionArch,
  type NativeExtensionArtifact,
  type NativeExtensionEmbeddedArtifact,
  type NativeExtensionEmbeddedErrorReason,
  type NativeExtensionEmbeddedMatrixTarget,
  type NativeExtensionEmbeddedTarget,
  type NativeExtensionFileArtifact,
  type NativeExtensionIdentitySource,
  type NativeExtensionExpectedIdentity,
  type NativeExtensionPackageArtifact,
  type NativeExtensionPackageTarget,
  type NativeExtensionTarget,
  type ResolvedNativeExtensionArtifact,
} from "./native-extension-artifact";
export {
  createTray,
  type CreateTrayHandle,
  type CreateTrayOptions,
  type OpenTrayRuntimeOptions,
} from "./sdk";
export {
  /**
   * Transport-close sentinel every request rejects with once the broker
   * connection dies (socket close, error, or completed graceful close).
   * Consumers match on this message to treat a dead backend as the desired
   * end state (e.g. quit paths racing their own teardown).
   */
  BROKER_CONNECTION_CLOSED_MESSAGE,
  /** Generic core-client rejection code for pending deferred operations on transport death. */
  EXTENSION_TRANSPORT_CLOSED_CODE,
  /** Typed rejection for deferred-operation terminals and transport-close deaths. */
  ExtensionOperationError,
  /** Typed handshake rejection when the broker Ready frame carries a different protocol version. */
  BrokerProtocolVersionError,
} from "./local-broker";
export type {
  OpenTrayAppBundleOptions,
  OpenTrayAppLaunchOptions,
} from "@opentray/packaging";
export {
  AppIconVariantNotFoundError,
  DEFAULT_APP_ICON_VARIANT,
  InvalidAppIconError,
  validateAppIcon,
} from "./app-icon";
export {
  type CreateTrayCheckItem,
  type CreateTrayItem,
  type CreateTrayMenu,
  type CreateTrayMenu as TrayMenu,
  type CreateTrayMenuClickHandler,
  type CreateTrayMenuItem,
  type CreateTrayRadioItem,
  type CreateTraySeparatorItem,
  type CreateTraySubmenuItem,
} from "./menu-input";
export {
  createBrokerEndpointIdentity,
  formatBrokerEndpointName,
  formatBrokerStateRoot,
  formatUnixSocketPath,
  formatWindowsPipeName,
  isSupportedProtocolVersion,
  EXTENSION_EVENT_RECORD_MAX_BYTES,
  PROTOCOL_VERSION,
  type AppId,
  type AppEvent,
  type AppIdentity,
  type AppIcon,
  type AppIconAsset,
  type AppIconSource,
  type AppIconVariant,
  type AppIconVariantOf,
  type AppOptions,
  type AppRef,
  type BrokerEndpointIdentity,
  type BrokerEndpointIdentityOptions,
  type ClientFrame,
  type ClientRequestFrame,
  type CommandScope,
  type DarwinIcon,
  type DarwinIconText,
  type ExpectedExtensionIdentity,
  type ExtensionArtifactTarget,
  type ExtensionEnvelope,
  type ExtOperationPayload,
  type Icon,
  type IconCandidates,
  type IconImage,
  type IconText,
  type LinuxIcon,
  type Menu,
  type MenuItem,
  type MenuItemId,
  type MouseButton,
  type Rect,
  type ServerFrame,
  type SimpleIcon,
  type Tooltip,
  type TrayBoundsKind,
  type TrayBoundsResult,
  type TrayEvent,
  type TrayId,
  type TrayOptions,
  type Icon as TrayIcon,
  type Tooltip as TrayTooltip,
  type TypedExtensionError,
  type Win32Icon,
} from "@opentray/spec";
