[package]
name = "opentray-ext-webview"
description = "OpenTray WebView dynamic extension ABI provider."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
opentray-spec.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = ["NSApplication", "NSGraphics", "NSView", "NSWindow"] }
objc2-foundation = { version = "0.3.2", features = ["NSGeometry", "NSString"] }
raw-window-handle = { version = "0.6.2", features = ["std"] }
wry = { version = "0.55.1", default-features = false, features = ["os-webview"] }
