// Orthogonal intents (2026-08-16; owner round-9 demands: startup terminal
// PTY streaming, shell window, tray icon wiring, multi-port monitor with
// (detached) title marking):
// 1. Render the generated app entry from the frozen config as one real TS
//    template literal (compile-checked here; no string surgery at build time).
// 2. Shell mode: window opens immediately, command runs through a PTY, ports
//    are monitored and detaches mark the window title.
// 3. Plain mode: wait-for-service window with favicon/title sync.
// 4. Tray icon: config asset → platform icon candidates (darwin template
//    variant for solid art), text-only fallback otherwise.
import type { ScaffoldAppConfig } from "./scaffold";

/** The generated app entry: supervises the command, owns tray + window. */
export const createEntrySource = (config: ScaffoldAppConfig): string => `#!/usr/bin/env node
// Generated by create-opentray. Supervises the recorded command and hosts it
// in an OpenTray tray + appMode window. Quit lives in the tray menu.
import { spawn, execFile, spawnSync } from "node:child_process";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import http from "node:http";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createTray } from "opentray";
import { WebviewExt } from "@opentray/ext-webview";

const PROJECT_DIR = dirname(fileURLToPath(import.meta.url));

// App Launch Law: persist the ABSOLUTE JS runtime. Under a Bun-hosted
// wizard, execPath is bun — resolve node's real path once at startup
// instead of persisting a bare PATH lookup (launchd's PATH is minimal).
const nodeRuntime = () => {
  if (process.versions.bun === undefined) return process.execPath;
  try {
    const found = spawnSync("which", ["node"], { encoding: "utf8" }).stdout?.trim() ?? "";
    if (found.length > 0) return found;
  } catch { /* fall through */ }
  return "node";
};
const READY_MARK_PREFIX = "opentray: ready";

const config = ${JSON.stringify(config, null, 2)};

const appLogPath = resolve(PROJECT_DIR, "app.log");
await mkdir(dirname(appLogPath), { recursive: true });
const logSink = appendFile.bind(undefined, appLogPath);

const shellOptions = ${JSON.stringify(config.shell ?? null)};
const hasShell = shellOptions !== null && (shellOptions.showTerminal || shellOptions.showAddressBar);
const showTerminal = shellOptions !== null && shellOptions.showTerminal === true;
const shellApi = hasShell ? await import("./app-shell-server.mjs") : null;

// Configured env overlay (advanced command options); empty by default.
const commandEnv = ${JSON.stringify(config.command.env ?? {})};

let command;
let commandExited = false;
if (showTerminal) {
  // Startup terminal (advanced option): run the command through a PTY and
  // stream its bytes to the shell UI — the same tab experience the wizard has.
  let ptyModule;
  try {
    ptyModule = await import("@lydell/node-pty");
  } catch {
    ptyModule = null;
  }
  const cwd = resolve(PROJECT_DIR, config.command.cwd);
  if (ptyModule !== null) {
    const pty = ptyModule.spawn(config.command.command, [...config.command.args], {
      name: "xterm-256color",
      cols: 100,
      rows: 30,
      cwd,
      env: { ...process.env, ...commandEnv, TERM: "xterm-256color" },
    });
    shellApi?.registerPty(pty);
    pty.onData((chunk) => {
      void logSink(chunk, "utf8");
      shellApi?.pushOutput(chunk);
    });
    const exited = new Promise((resolvePromise) => {
      pty.onExit(({ exitCode }) => {
        commandExited = true;
        void logSink(\`[command exited \${exitCode}]\n\`, "utf8");
        resolvePromise(exitCode);
      });
    });
    command = { pid: pty.pid, exited, kill: async () => { try { pty.kill(); } catch {} await exited; } };
  } else {
    await logSink("[create-opentray] @lydell/node-pty unavailable; startup terminal degraded to pipes\\n", "utf8");
  }
}
if (command === undefined) {
  const child = spawn(config.command.command, [...config.command.args], {
    cwd: resolve(PROJECT_DIR, config.command.cwd),
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, ...commandEnv },
    windowsHide: true,
  });
  child.stdout.setEncoding("utf8");
  child.stderr.setEncoding("utf8");
  child.stdout.on("data", (chunk) => { void logSink(chunk, "utf8"); shellApi?.pushOutput(chunk); });
  child.stderr.on("data", (chunk) => { void logSink(chunk, "utf8"); shellApi?.pushOutput(chunk); });
  child.once("exit", (code) => {
    commandExited = true;
    void logSink(\`[command exited \${code ?? "signal"}]\n\`, "utf8");
  });
  command = child;
}

const killCommand = async () => {
  if (commandExited) return;
  // command.kill is always a function here: the PTY wrapper (shell mode) or
  // the ChildProcess (plain mode). The PTY wrapper tears down the session
  // tree; plain spawns SIGTERM the direct child.
  await command.kill();
};

let appIcon;
try {
  const manifest = JSON.parse(await readFile(resolve(PROJECT_DIR, "app-icon", "app-icon.json"), "utf8"));
  // The manifest stores project-relative source paths; OpenTray validates file
  // sources against the caller's cwd, so canonicalize them to absolute paths
  // before dispatch (a reused broker cwd must never reinterpret App identity).
  appIcon = manifest.appIcon.map((asset) => (
    asset.source?.type === "file" && !asset.source.path.startsWith("/")
      ? { ...asset, source: { ...asset.source, path: resolve(PROJECT_DIR, "app-icon", asset.source.path) } }
      : asset
  ));
} catch {
  appIcon = undefined;
}

const httpAnswers = (port) => new Promise((resolvePromise) => {
  const request = http.get({ host: "127.0.0.1", port, path: "/", timeout: 1500 }, (response) => {
    response.resume();
    resolvePromise(response.statusCode !== undefined && response.statusCode > 0);
  });
  request.once("timeout", () => { request.destroy(); resolvePromise(false); });
  request.once("error", () => resolvePromise(false));
});

const listProcessTreePids = async (rootPid) => {
  if (process.platform === "win32") return [rootPid];
  const pids = new Set([rootPid]);
  const frontier = [rootPid];
  while (frontier.length > 0) {
    const pid = frontier.pop();
    const children = await new Promise((resolvePromise) => {
      execFile("pgrep", ["-P", String(pid)], (error, stdout) => {
        resolvePromise(error ? [] : stdout.split("\\n").map((line) => Number(line)).filter((n) => Number.isInteger(n) && n > 0));
      });
    });
    for (const child of children) {
      if (!pids.has(child)) { pids.add(child); frontier.push(child); }
    }
  }
  return [...pids];
};

const listOwnedListeningPorts = async (rootPid) => {
  if (process.platform === "win32") return [];
  const mine = new Set((await listProcessTreePids(rootPid)).map((pid) => String(pid)));
  const output = await new Promise((resolvePromise) => {
    execFile("lsof", ["-F", "pPn", "-nP", "-i", "TCP", "-sTCP:LISTEN"], (error, stdout) => {
      resolvePromise(error ? "" : stdout);
    });
  });
  const ports = new Set();
  let currentPid = "";
  for (const line of output.split("\\n")) {
    if (line.length === 0) continue;
    const tag = line[0];
    const value = line.slice(1);
    if (tag === "p") currentPid = value;
    else if (tag === "n" && currentPid !== "" && mine.has(currentPid)) {
      const port = Number(value.split(":").pop());
      if (Number.isInteger(port) && port > 0) ports.add(port);
    }
  }
  return [...ports];
};

// PORTS COME EXCLUSIVELY FROM SNIFFING (owner law): scan the command's
// process tree for listening ports and HTTP-verify each candidate. The
// recorded preview port is informational only and is never addressed
// without verification; dynamic-port commands (listen(0)) therefore behave
// identically to fixed-port ones.
const sniffServicePort = async (timeoutMs) => {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const owned = await listOwnedListeningPorts(command.pid).catch(() => []);
    for (const port of owned.filter((p) => p > 0)) {
      if (await httpAnswers(port)) return port;
    }
    if (Date.now() > deadline) {
      throw new Error("no HTTP service found among the command's listening ports within " + timeoutMs + "ms");
    }
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 500));
  }
};

// Shell mode: start the local shell server first so windows can open
// immediately; the monitor below sniffs services continuously.
const shellPort = hasShell ? await shellApi.listenShell() : null;

// Plain mode needs one verified address before opening its single window;
// shell mode defers entirely to the continuous monitor.
const servicePort = hasShell
  ? null
  : await sniffServicePort(30_000).catch(async (error) => {
      await logSink(\`[create-opentray] \${error.message}\\n\`, "utf8");
      await killCommand();
      throw error;
    });

const trayIcon = ${JSON.stringify(config.trayIcon ?? null)};
const trayIconCandidates = trayIcon === null
  ? {}
  : trayIcon.template && process.platform === "darwin"
    ? { "darwin-icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path), isTemplate: true } }
    : { "icon-only": { type: "file", path: resolve(PROJECT_DIR, trayIcon.path) } };

const tray = await createTray({
  id: config.appId,
  tooltip: { title: config.appName, description: \`\${config.appName} (OpenTray)\` },
  icon: Object.keys(trayIconCandidates).length > 0
    ? trayIconCandidates
    : { "text-only": "${config.appName.replace(/['"\\]/gu, "").slice(0, 2) || "A"}" },
  menu: { items: [
    { type: "item", id: 1, title: \`Show \${config.appName}\`, primaryEvent: true },
    { type: "separator" },
    { type: "item", id: 2, title: "Quit" },
  ] },
}, {
  appId: config.appId,
  appName: config.appName,
  ...(appIcon === undefined ? {} : { appIcon }),
  appLaunch: {
    // The generated entry may embed a native PTY (@lydell/node-pty), which
    // requires a Node host — cold launches must not inherit a Bun execPath.
    command: nodeRuntime(),
    args: [resolve(PROJECT_DIR, "main.mjs")],
    cwd: PROJECT_DIR,
  },
});

const baseTitle = config.appName;
const showAddressBar = shellOptions !== null && shellOptions.showAddressBar === true;

// Dedicated windows (round 9b): one terminal window when enabled, one window
// per listened port — an address-bar wrapper page when enabled, the direct
// service URL otherwise. No embedded tabs panel.
// Each window gets its OWN extension mount (tray.extend per window): one
// mount owns exactly one native webview slot, so dedicated windows never
// collide on content.
const serviceWindows = new Map();
let terminalWindow = null;

const ensureServiceWindow = async (port) => {
  if (serviceWindows.has(port)) return;
  const direct = \`http://127.0.0.1:\${port}\`;
  const url = showAddressBar && shellPort !== null
    ? \`http://127.0.0.1:\${shellPort}/browse.html?url=\${encodeURIComponent(direct)}\`
    : direct;
  const win = tray.extend(WebviewExt).createWebviewWindow({
    url,
    width: config.window.width,
    height: config.window.height,
    title: baseTitle,
    style: { appMode: true, autoHide: false, keepOnTop: false },
    ...(showAddressBar ? {} : { titleSync: { documentToWindow: true, windowToDocument: true } }),
    ...(showAddressBar ? {} : { iconSync: { faviconToWindow: true, windowToFavicon: true } }),
  });
  serviceWindows.set(port, { win, detached: false });
  await win.show().catch(() => {});
};

if (showTerminal && shellPort !== null) {
  terminalWindow = tray.extend(WebviewExt).createWebviewWindow({
    url: \`http://127.0.0.1:\${shellPort}/terminal.html\`,
    width: 900,
    height: 560,
    title: \`\${baseTitle} — Terminal\`,
    style: { appMode: true, autoHide: false, keepOnTop: false },
  });
  await terminalWindow.show().catch(() => {});
}

// Plain mode: the first verified port opens immediately through the SAME
// per-port window machinery the monitor uses (no duplicate window object);
// additional ports get their own windows as the monitor verifies them.
if (!hasShell && servicePort !== null) {
  await ensureServiceWindow(servicePort);
}

{
  // Continuous owned-port monitor (BOTH modes): every HTTP-verified listening
  // port gets its own window, and a port that stops listening marks THAT
  // window's title (detached). Spec: one window per listened port, never
  // gated on shell mode.
  const seenPorts = new Set();
  const verifiedPorts = new Set();
  const monitor = setInterval(async () => {
    try {
      const owned = await listOwnedListeningPorts(command.pid).catch(() => []);
      const listening = owned.filter((port) => port > 0);
      // Spec: owned-listener scan PLUS HTTP verification before a port is
      // ever addressed — the monitor never adopts a non-HTTP listener.
      for (const port of listening) {
        if (!verifiedPorts.has(port) && (await httpAnswers(port))) {
          verifiedPorts.add(port);
        }
      }
      for (const port of verifiedPorts) seenPorts.add(port);
      const services = [...seenPorts].map((port) => ({
        port,
        detached: !listening.includes(port),
      }));
      shellApi?.setServices(services);
      for (const service of services) {
        if (!service.detached) await ensureServiceWindow(service.port);
        const entry = serviceWindows.get(service.port);
        if (entry !== undefined && Boolean(entry.detached) !== Boolean(service.detached)) {
          entry.detached = Boolean(service.detached);
          const title = service.detached ? \`\${baseTitle} (detached)\` : baseTitle;
          await entry.win.setTitle(title).catch(() => {});
        }
      }
    } catch {
      /* monitor tick */
    }
  }, 1500);
  const stopMonitor = () => clearInterval(monitor);
  process.once("exit", stopMonitor);
}

const quit = async () => {
  for (const { win } of serviceWindows.values()) {
    try { await win.destroy(); } catch {}
  }
  serviceWindows.clear();
  if (terminalWindow !== null) {
    try { await terminalWindow.destroy(); } catch {}
  }
  await tray.destroy();
  await killCommand();
  process.exit(0);
};

tray.onMenuClick(({ itemId }) => {
  if (itemId === 1) {
    const target = terminalWindow !== null
      ? terminalWindow
      : serviceWindows.size > 0
        ? [...serviceWindows.values()][0].win
        : null;
    if (target === null) return;
    void target.isVisible().then(async (visible) => {
      if (visible) { await target.close(); } else { await target.toVisible(); }
    }).catch(() => {});
    return;
  }
  if (itemId === 2) void quit();
});

process.on("SIGINT", () => void quit());
process.on("SIGTERM", () => void quit());

console.log(\`\${READY_MARK_PREFIX} \${JSON.stringify({ appId: config.appId, ...(servicePort === null ? {} : { port: servicePort }) })}\`);

`;
