// Orthogonal intents (maintained 2026-07-22; original user request: create a
// locally hosted app from the frozen wizard form):
// 1. Write a self-contained consumer project that depends only on published packages.
// 2. Persist the frozen identity, command vector, and service port as app config.
// 3. Generate an entry that supervises the command and owns tray+window lifetime.

import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

import type { LaunchVector } from "./launch-vector";
import { createEntrySource } from "./entry-template";
import { shellServerSource } from "./shell-server-template";

export { createEntrySource };
import { toProjectDirectoryName } from "./app-id";

export interface ScaffoldAppConfig {
  readonly schemaVersion: 1;
  readonly appId: string;
  readonly appName: string;
  readonly command: LaunchVector;
  readonly service: { readonly port: number };
  readonly window: { readonly width: number; readonly height: number };
  /** Tray icon asset (written by materialize); omitted → text-only tray. */
  readonly trayIcon?: { readonly path: string; readonly template: boolean };
  /** Generated-app shell (startup terminal / address-bar tabs). */
  readonly shell?: {
    readonly showTerminal: boolean;
    readonly showAddressBar: boolean;
  };
}

export interface ScaffoldOptions {
  readonly config: ScaffoldAppConfig;
  readonly targetDir: string;
  /** opentray/@opentray/ext-webview version range written into package.json. */
  readonly dependencyRange: string;
  /** Whether install will be skipped; only affects README guidance text. */
  readonly skipInstall?: boolean;
  /** Directory holding the prebuilt shell UI (copied to app-shell/ when the
   *  shell is enabled). */
  readonly shellAssetsDir?: string;
}

export interface ScaffoldResult {
  readonly projectDir: string;
  readonly entryPath: string;
  readonly configPath: string;
  readonly appIconDir: string;
  readonly writtenFiles: readonly string[];
}

/** Filenames that identify a directory as a create-opentray project. */
export const SCAFFOLD_MARKER_FILES = [
  "opentray.app.json",
  "main.mjs",
] as const;

export const writeScaffold = async (options: ScaffoldOptions): Promise<ScaffoldResult> => {
  const projectDir = resolve(options.targetDir);
  await mkdir(join(projectDir, "app-icon"), { recursive: true });

  const writtenFiles: string[] = [];
  const write = async (relative: string, content: string): Promise<void> => {
    const path = join(projectDir, relative);
    await mkdir(join(path, ".."), { recursive: true });
    await writeFile(path, content, "utf8");
    writtenFiles.push(relative);
  };

  await write("package.json", createPackageJson(options));
  await write("opentray.app.json", `${JSON.stringify(options.config, null, 2)}\n`);
  await write("main.mjs", createEntrySource(options.config));
  const shell = options.config.shell;
  if (shell !== undefined && (shell.showTerminal || shell.showAddressBar)) {
    await write("app-shell-server.mjs", createShellServerSource(options.config));
    if (options.shellAssetsDir !== undefined) {
      const { cp } = await import("node:fs/promises");
      await cp(options.shellAssetsDir, join(projectDir, "app-shell"), { recursive: true });
      writtenFiles.push("app-shell/");
    }
  }
  await write("README.md", createReadme(options));
  await write(".gitignore", ["node_modules/\n", "app.log\n", "dist/\n"].join(""));

  return {
    projectDir,
    entryPath: join(projectDir, "main.mjs"),
    configPath: join(projectDir, "opentray.app.json"),
    appIconDir: join(projectDir, "app-icon"),
    writtenFiles,
  };
};

const createPackageJson = (options: ScaffoldOptions): string => {
  const shell = options.config.shell;
  const dependencies: Record<string, string> = {
    opentray: options.dependencyRange,
    "@opentray/ext-webview": options.dependencyRange,
  };
  if (shell !== undefined && shell.showTerminal) {
    // The startup terminal streams the command through a native PTY.
    dependencies["@lydell/node-pty"] = "^1.1.0";
  }
  return `${JSON.stringify(
    {
      name: toProjectDirectoryName(options.config.appId),
      version: "0.1.0",
      private: true,
      type: "module",
      description: `${options.config.appName} — OpenTray-hosted app generated by create-opentray`,
      scripts: {
        start: "node main.mjs",
      },
      dependencies,
    },
    null,
    2,
  )}\n`;
};

const createReadme = (options: ScaffoldOptions): string => `# ${options.config.appName}

Generated by \`create-opentray\`. This app supervises the recorded start
command, hosts it in an OpenTray tray + application window, and can be pinned
to the taskbar (Windows) or Dock (macOS).

## Run

${options.skipInstall === true ? "Install dependencies first, then:" : ""}
\`\`\`bash
npm run start
\`\`\`

- Service: ${options.config.service.port > 0 ? `http://127.0.0.1:${options.config.service.port} (preview hint; re-sniffed at runtime)` : "sniffed at runtime from the command's owned listening ports"}
- Command: \`${options.config.command.command} ${options.config.command.args.join(" ")}\`
- Logs: \`app.log\`

## Files

- \`opentray.app.json\` — frozen identity and launch vector
- \`app-icon/\` — generated platform icon catalog (ICNS/ICO/PNG)
- \`main.mjs\` — app entry: supervises the command and owns the tray session
`;

/** Shell server entry source: static UI + PTY stream + port state (round 9). */
export const createShellServerSource = (config: ScaffoldAppConfig): string =>
  shellServerSource({
    commandDisplay: `${config.command.command} ${config.command.args.join(" ")}`.trim(),
  });
