// Orthogonal intents (maintained 2026-07-22; original user request: create a
// locally hosted app from the frozen wizard form):
// 1. Write a self-contained consumer project that depends only on published packages.
// 2. Persist the frozen identity, command vector, and service port as app config.
// 3. Generate an entry that supervises the command and owns tray+window lifetime.

import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

import type { LaunchVector } from "./launch-vector";
import { toProjectDirectoryName } from "./app-id";

export interface ScaffoldAppConfig {
  readonly schemaVersion: 1;
  readonly appId: string;
  readonly appName: string;
  readonly command: LaunchVector;
  readonly service: { readonly port: number };
  readonly window: { readonly width: number; readonly height: number };
}

export interface ScaffoldOptions {
  readonly config: ScaffoldAppConfig;
  readonly targetDir: string;
  /** opentray/@opentray/ext-webview version range written into package.json. */
  readonly dependencyRange: string;
  /** Whether install will be skipped; only affects README guidance text. */
  readonly skipInstall?: boolean;
}

export interface ScaffoldResult {
  readonly projectDir: string;
  readonly entryPath: string;
  readonly configPath: string;
  readonly appIconDir: string;
  readonly writtenFiles: readonly string[];
}

/** Filenames that identify a directory as a create-opentray project. */
export const SCAFFOLD_MARKER_FILES = [
  "opentray.app.json",
  "main.mjs",
] as const;

export const writeScaffold = async (options: ScaffoldOptions): Promise<ScaffoldResult> => {
  const projectDir = resolve(options.targetDir);
  await mkdir(join(projectDir, "app-icon"), { recursive: true });

  const writtenFiles: string[] = [];
  const write = async (relative: string, content: string): Promise<void> => {
    const path = join(projectDir, relative);
    await mkdir(join(path, ".."), { recursive: true });
    await writeFile(path, content, "utf8");
    writtenFiles.push(relative);
  };

  await write("package.json", createPackageJson(options));
  await write("opentray.app.json", `${JSON.stringify(options.config, null, 2)}\n`);
  await write("main.mjs", createEntrySource(options.config));
  await write("README.md", createReadme(options));
  await write(".gitignore", ["node_modules/\n", "app.log\n", "dist/\n"].join(""));

  return {
    projectDir,
    entryPath: join(projectDir, "main.mjs"),
    configPath: join(projectDir, "opentray.app.json"),
    appIconDir: join(projectDir, "app-icon"),
    writtenFiles,
  };
};

const createPackageJson = (options: ScaffoldOptions): string =>
  `${JSON.stringify(
    {
      name: toProjectDirectoryName(options.config.appId),
      version: "0.1.0",
      private: true,
      type: "module",
      description: `${options.config.appName} — OpenTray-hosted app generated by create-opentray`,
      scripts: {
        start: "node main.mjs",
      },
      dependencies: {
        opentray: options.dependencyRange,
        "@opentray/ext-webview": options.dependencyRange,
      },
    },
    null,
    2,
  )}\n`;

const createReadme = (options: ScaffoldOptions): string => `# ${options.config.appName}

Generated by \`create-opentray\`. This app supervises the recorded start
command, hosts it in an OpenTray tray + application window, and can be pinned
to the taskbar (Windows) or Dock (macOS).

## Run

${options.skipInstall === true ? "Install dependencies first, then:" : ""}
\`\`\`bash
npm run start
\`\`\`

- Service: ${`http://127.0.0.1:${options.config.service.port}`}
- Command: \`${options.config.command.command} ${options.config.command.args.join(" ")}\`
- Logs: \`app.log\`

## Files

- \`opentray.app.json\` — frozen identity and launch vector
- \`app-icon/\` — generated platform icon catalog (ICNS/ICO/PNG)
- \`main.mjs\` — app entry: supervises the command and owns the tray session
`;

/** The generated app entry: supervises the command, owns tray + window. */
export const createEntrySource = (config: ScaffoldAppConfig): string => `#!/usr/bin/env node
// Generated by create-opentray. Supervises the recorded command and hosts it
// in an OpenTray tray + appMode window. Quit lives in the tray menu.
import { spawn, execFile } from "node:child_process";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import net from "node:net";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createTray } from "opentray";
import { WebviewExt } from "@opentray/ext-webview";

const PROJECT_DIR = dirname(fileURLToPath(import.meta.url));
const READY_MARK_PREFIX = "opentray: ready";

const config = ${JSON.stringify(config, null, 2)};

const appLogPath = resolve(PROJECT_DIR, "app.log");
await mkdir(dirname(appLogPath), { recursive: true });
const logSink = appendFile.bind(undefined, appLogPath);

const command = spawn(config.command.command, [...config.command.args], {
  cwd: resolve(PROJECT_DIR, config.command.cwd),
  stdio: ["ignore", "pipe", "pipe"],
  env: process.env,
  windowsHide: true,
});
command.stdout.setEncoding("utf8");
command.stderr.setEncoding("utf8");
command.stdout.on("data", (chunk) => void logSink(chunk, "utf8"));
command.stderr.on("data", (chunk) => void logSink(chunk, "utf8"));
command.once("exit", (code) => {
  void logSink(\`[command exited \${code ?? "signal"}]\\n\`, "utf8");
});

const waitForPort = (port, timeoutMs) => new Promise((resolvePromise, rejectPromise) => {
  const deadline = Date.now() + timeoutMs;
  const attempt = () => {
    const socket = net.connect(port, "127.0.0.1");
    socket.once("connect", () => { socket.destroy(); resolvePromise(true); });
    socket.once("error", () => {
      socket.destroy();
      if (Date.now() > deadline) {
        rejectPromise(new Error(\`service did not answer on 127.0.0.1:\${port} within \${timeoutMs}ms\`));
        return;
      }
      setTimeout(attempt, 150);
    });
  };
  attempt();
});

const killCommand = () => {
  if (command.exitCode !== null || command.signalCode !== null) return Promise.resolve();
  if (process.platform === "win32") {
    return new Promise((resolvePromise) => {
      execFile("taskkill", ["/PID", String(command.pid), "/T", "/F"], () => resolvePromise());
    });
  }
  try { process.kill(-command.pid, "SIGTERM"); } catch { command.kill("SIGTERM"); }
  return new Promise((resolvePromise) => command.once("exit", resolvePromise));
};

let appIcon;
try {
  const manifest = JSON.parse(await readFile(resolve(PROJECT_DIR, "app-icon", "app-icon.json"), "utf8"));
  appIcon = manifest.appIcon;
} catch {
  appIcon = undefined;
}

await waitForPort(config.service.port, 30_000).catch(async (error) => {
  await logSink(\`[create-opentray] \${error.message}\\n\`, "utf8");
  await killCommand();
  throw error;
});

const tray = await createTray({
  id: config.appId,
  tooltip: { title: config.appName, description: \`\${config.appName} (OpenTray)\` },
  icon: { "text-only": "${config.appName.replace(/['"\\]/gu, "").slice(0, 2) || "A"}" },
  menu: { items: [
    { type: "item", id: 1, title: \`Show \${config.appName}\`, primaryEvent: true },
    { type: "separator" },
    { type: "item", id: 2, title: "Quit" },
  ] },
}, {
  appId: config.appId,
  appName: config.appName,
  ...(appIcon === undefined ? {} : { appIcon }),
  appLaunch: {
    command: process.execPath,
    args: [resolve(PROJECT_DIR, "main.mjs")],
    cwd: PROJECT_DIR,
  },
});

const webview = tray.extend(WebviewExt).createWebviewWindow({
  url: \`http://127.0.0.1:\${config.service.port}\`,
  width: config.window.width,
  height: config.window.height,
  title: config.appName,
  style: { appMode: true, autoHide: false, keepOnTop: false },
  titleSync: { documentToWindow: true, windowToDocument: true },
  iconSync: { faviconToWindow: true, windowToFavicon: true },
});
await webview.show();

const quit = async () => {
  try { await webview.destroy(); } catch {}
  await tray.destroy();
  await killCommand();
  process.exit(0);
};

tray.onMenuClick(({ itemId }) => {
  if (itemId === 1) {
    void webview.isVisible().then(async (visible) => {
      if (visible) { await webview.close(); } else { await webview.toVisible(); }
    }).catch(() => {});
    return;
  }
  if (itemId === 2) void quit();
});

process.on("SIGINT", () => void quit());
process.on("SIGTERM", () => void quit());

console.log(\`\${READY_MARK_PREFIX} \${JSON.stringify({ appId: config.appId, port: config.service.port })}\`);
`;
